# fly.toml app configuration file generated for grace-index on 2023-06-30T13:17:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grace-index"
primary_region = "sea"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
